IMAGE_WIDTH = 1920
IMAGE_HEIGHT = 1080
TEXT_WIDTH = 600
TEXT_RIGHT_PADDING = 90
TEXT_BOTTOM_PADDING = 130
SHADOW_SIZE = 0.2
TEXT_SIZE = int(40 * 1.2)
VIDEO_FPS = 30
IMAGE_SCALING = 0.1
ICON_MARGIN = 50
ICON_SIZE = 64
LETTER_WIDTH = int(22 * 1.2)

DEMO = True
OVERLAY_ENABLED = False

TEXT_MODE = 'LEFT' # 'CENTER' - center, 'LEFT' - left, 'RIGHT' - right